version: "3"

services:
  ticker:
    build:
      context: .
      dockerfile: Dockerfile
    image: rw/ticker:latest
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
    volumes:
      - ./ticker:/ticker
      - ./tests:/tests
    entrypoint:
      - poetry
      - run
      - uvicorn
      - ticker.entrypoints.app_controller:app
      - --host=0.0.0.0
      - --port=80
      - --reload
    ports:
      - "80:80"

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_DATABASE=ticker
      - USE_MOCK_VENDOR_PROXY=False
    ports:
      - "33061:3306"
    # XXX 한글 저장 시 인코딩 설정
    command:
       - --character-set-server=utf8mb4
       - --collation-server=utf8mb4_unicode_ci
