version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ft/ticker:latest
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ./ticker:/ticker
      - ./tests:/tests
    entrypoint:
      - poetry
      - run
      - uvicorn
      - ticker.entrypoints.app_controller:app
      - --host=0.0.0.0
      - --port=80
      - --reload
    ports:
      - "80:80"

  mysql:
    image: mysql:8.0.31-debian
    # XXX for mac m1
    # platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_DATABASE=ticker
    ports:
      - "33061:3306"
    # XXX 한글 저장 시 인코딩 설정
    command:
      - --character-set-server=utf8mb4      - --collation-server=utf8mb4_unicode_ci
